Ajustando novo job

diff --git a/.github/workflows/reusable-ci.yml b/.github/workflows/reusable-ci.yml
--- a/.github/workflows/reusable-ci.yml
+++ b/.github/workflows/reusable-ci.yml
@@ -40,33 +40,50 @@ jobs:
 
       - name: Run Tests
         run: mvn test
-  
+
+      - name: Upload JaCoCo report
+        uses: actions/upload-artifact@v4
+        with:
+          name: jacoco-report
+          path: target/site/jacoco/jacoco.xml
+
   quality-gate:
     if: ${{ inputs.enable_jacoco }}
     needs: unit-test
     runs-on: ubuntu-latest
     steps:
-      - name: Valida cobertura de teste
-        id: coverage
-        run: |
-          LINE_COVERAGE=$(xmllint --xpath "string(//report/counter[@type='LINE']/@covered)" target/site/jacoco/jacoco.xml)
-          LINE_MISSED=$(xmllint --xpath "string(//report/counter[@type='LINE']/@missed)" target/site/jacoco/jacoco.xml)
+      - name: Download JaCoCo report
+        uses: actions/download-artifact@v4
+        with:
+          name: jacoco-report
+          path: jacoco
 
-          TOTAL=$((LINE_COVERAGE + LINE_MISSED))
-          if [ "$TOTAL" -eq 0 ]; then
-            echo "Nenhuma linha encontrada no relatório do JaCoCoNo. Falhou."
+      - name: Validate test coverage
+        run: |
+          REPORT="jacoco/jacoco.xml"
+
+          if [ ! -f "$REPORT" ]; then
+            echo "❌ Coverage report not found at $REPORT"
             exit 1
           fi
 
-          PERCENT=$(( 100 * LINE_COVERAGE / TOTAL ))
-          echo "Cobertura total de linhas: $PERCENT%"
+          LINE_COVERED=$(xmllint --xpath "string(//report/counter[@type='LINE']/@covered)" "$REPORT")
+          LINE_MISSED=$(xmllint --xpath "string(//report/counter[@type='LINE']/@missed)" "$REPORT")
+
+          TOTAL=$((LINE_COVERED + LINE_MISSED))
+          if [ "$TOTAL" -eq 0 ]; then
+            echo "❌ No lines found in the JaCoCo report. Failing..."
+            exit 1
+          fi
+
+          PERCENT=$(( 100 * LINE_COVERED / TOTAL ))
+          echo "ℹ️ Total line coverage: $PERCENT%"
 
           if [ "$PERCENT" -lt 70 ]; then
-            echo "❌ Cobertura de código $PERCENT% é menor que o limite de (70%)"
+            echo "❌ Code coverage is $PERCENT%, which is below the threshold of 70%"
             exit 1
           else
-            echo "✅ Cobertura de código de $PERCENT% é aceitável"
-          fi
+            ech
 
   code-analysis:
     if: ${{ inputs.enable_sonar }}
